### ISSUE TITLE
minikube not showing registry-creds as an addon

### ISSUE THREAD

**Issue by madhurranjan** [upmc-enterprises/registry-creds#27]
Hi,

Just installed minikube 0.15 but I don't see registry-creds as an add on. I see ecr-creds as a default add-on and i can also get registry-creds RC up and running but it doesn't seem to work while it tries to pull an image from GCR. Wondering what's wrong here.

**Comment by stevesloka** [comment]
Hey @madhurranjan, so we did a bit of renaming. `awsecr-creds` was the first iteration of this which got credentials from AWS ECR. Since then we added support for GCR and renamed the repo to `registry-creds` to try and make it less confusing. 

Until a new build goes out, you can enable the creds but use the image: `upmcenterprises/registry-creds:1.4`, and follow the instructions on how to setup (https://github.com/upmc-enterprises/registry-creds#how-to-setup-running-in-gcr) and you should be good.

**Comment by stevesloka** [comment]
Minikube 0.16 is out, you can download here (https://github.com/kubernetes/minikube/releases/tag/v0.16.0) which was the renamed addon present.
